#!/bin/bash
set -e
set -x

# configure tomcat admin user/password
TOMCAT_ADMIN_USER=${TOMCAT_ADMIN_USER:-admin}
TOMCAT_ADMIN_PASSWORD=${TOMCAT_ADMIN_PASSWORD:-admin}
sed 's,{{TOMCAT_ADMIN_USER}},'"${TOMCAT_ADMIN_USER}"',g' -i /opt/tomcat/conf/tomcat-users.xml
sed 's,{{TOMCAT_ADMIN_PASSWORD}},'"${TOMCAT_ADMIN_PASSWORD}"',g' -i /opt/tomcat/conf/tomcat-users.xml

# mysql db
DB_TYPE=mysql
DB_HOST=$MYSQL_PORT_3306_TCP_ADDR
DB_PORT=$MYSQL_PORT_3306_TCP_PORT
DB_NAME=$DB_NAME
DB_USER=$DB_USER
DB_PASS=$DB_PASS

echo "Environment variables"
echo "User: "${DB_USER}
echo "Pass: "${DB_PASS}
echo "HOST: "${DB_HOST}
echo "DBName: "${DB_NAME}

#sed 's/{{DB_PORT}}/'"${DB_PORT}"'/g' -i /assets/config/db.properties
sed 's/{{DB_HOST}}/'"${DB_HOST}"'/g' -i /assets/config/db.properties
#sed 's/{{DB_NAME}}/'"${DB_NAME}"'/g' -i /assets/config/db.properties
#sed 's/{{DB_USER}}/'"${DB_USER}"'/g' -i /assets/config/db.properties
#sed 's/{{DB_PASS}}/'"${DB_PASS}"'/g' -i /assets/config/db.properties

cp -f /assets/config/db.properties /opt/tomcat/webapps/activiti-rest/WEB-INF/classes
cp -f /assets/config/db.properties /opt/tomcat/webapps/activiti-explorer/WEB-INF/classes

/opt/tomcat/bin/catalina.sh run
